apiVersion: v1
kind: service
metadata: 
  name: python
  labels:
    app: python
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: clusterIP
