name: multiplejobs

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        run: actions@checkoutv4
      - name: Read File
        run: cat README.md
